/*
 * ToolbarPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package edu.chl.tda367.booleancircuits.view;

import javax.swing.*;

/**
 * 
 * @author Boel
 */
public class ToolbarPanel extends javax.swing.JPanel {

	/** Creates new form ToolbarPanel */
	public ToolbarPanel() {
		initComponents();
	}

	/**
	 * Returns the cut button
	 * 
	 * @return JButton
	 */
	public JButton getCutButton() {
		return cutButton;
	}

	/**
	 * Returns the copy button
	 * 
	 * @return JButton
	 */
	public JButton getCopyButton() {
		return copyButton;
	}

	/**
	 * Returns the new works space button
	 * 
	 * @return JButton
	 */
	public JButton getNewWorkspaceButton() {
		return newWorkspaceButton;
	}

	/**
	 * Returns the open file button
	 * 
	 * @return JButton
	 */
	public JButton getOpenFileButton() {
		return openFileButton;
	}

	/**
	 * Returns the paste button
	 * 
	 * @return JButton
	 */
	public JButton getPasteButton() {
		return pasteButton;
	}

	/**
	 * Returns the redo button
	 * 
	 * @return JButton
	 */
	public JButton getRedoButton() {
		return redoButton;
	}

	/**
	 * Returns the save all button
	 * 
	 * @return JButton
	 */
	public JButton getSaveAllButton() {
		return saveAllButton;
	}

	/**
	 * Returns the save as component button
	 * 
	 * @return JButton
	 */
	public JButton getSaveAsComponentButton() {
		return saveAsComponentButton;
	}

	/**
	 * Returns the save button
	 * 
	 * @return JButton
	 */
	public JButton getSaveButton() {
		return saveButton;
	}

	/**
	 * Returns the undo button
	 * @return JButton
	 */
	public JButton getUndoButton() {
		return undoButton;
	}

	/**
	 * Sets all the toolbar icons.
	 */
	public void initIcons() {
		newWorkspaceButton.setIcon(new ImageIcon(
				"Resources/Icons/New-Document-icon.png"));
		openFileButton.setIcon(new ImageIcon("Resources/Icons/Open-icon.png"));
		saveButton.setIcon(new ImageIcon("Resources/Icons/Save-icon.png"));
		saveAllButton
				.setIcon(new ImageIcon("Resources/Icons/save-all-icon.png"));
		saveAsComponentButton.setIcon(new ImageIcon(
				"Resources/Icons/save-component.png"));
		cutButton.setIcon(new ImageIcon("Resources/Icons/cut-icon.png"));
		copyButton.setIcon(new ImageIcon("Resources/Icons/copy-icon.png"));
		pasteButton.setIcon(new ImageIcon("Resources/Icons/paste-icon.png"));
		undoButton.setIcon(new ImageIcon("Resources/Icons/Undo-icon.png"));
		redoButton.setIcon(new ImageIcon("Resources/Icons/Redo-icon.png"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		newWorkspaceButton = new javax.swing.JButton();
		openFileButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		saveAllButton = new javax.swing.JButton();
		saveAsComponentButton = new javax.swing.JButton();
		cutButton = new javax.swing.JButton();
		copyButton = new javax.swing.JButton();
		pasteButton = new javax.swing.JButton();
		undoButton = new javax.swing.JButton();
		redoButton = new javax.swing.JButton();

		setPreferredSize(new java.awt.Dimension(220, 24));
		setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		newWorkspaceButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(newWorkspaceButton);

		openFileButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(openFileButton);

		saveButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(saveButton);

		saveAllButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(saveAllButton);

		saveAsComponentButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(saveAsComponentButton);

		cutButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(cutButton);

		copyButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(copyButton);

		pasteButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(pasteButton);

		undoButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(undoButton);

		redoButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(redoButton);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton copyButton;
	private javax.swing.JButton cutButton;
	private javax.swing.JButton newWorkspaceButton;
	private javax.swing.JButton openFileButton;
	private javax.swing.JButton pasteButton;
	private javax.swing.JButton redoButton;
	private javax.swing.JButton saveAllButton;
	private javax.swing.JButton saveAsComponentButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JButton undoButton;
	// End of variables declaration//GEN-END:variables

}