/*
 * ToolbarPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package edu.chl.tda367.booleancircuits.view;

/**
 *
 * @author  __USER__
 */
public class ToolbarPanel extends javax.swing.JPanel {

	/** Creates new form ToolbarPanel */
	public ToolbarPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		newWorkspaceButton = new javax.swing.JButton();
		openFileButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		saveAllButton = new javax.swing.JButton();
		saveAsComponentButton = new javax.swing.JButton();
		cutButton = new javax.swing.JButton();
		copyButton = new javax.swing.JButton();
		pasteButton = new javax.swing.JButton();
		undoButton = new javax.swing.JButton();
		redoButton = new javax.swing.JButton();

		setPreferredSize(new java.awt.Dimension(220, 24));
		setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		newWorkspaceButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(newWorkspaceButton);

		openFileButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(openFileButton);

		saveButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(saveButton);

		saveAllButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(saveAllButton);

		saveAsComponentButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(saveAsComponentButton);

		cutButton.setPreferredSize(new java.awt.Dimension(20, 20));
		cutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cutButtonActionPerformed(evt);
			}
		});
		add(cutButton);

		copyButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(copyButton);

		pasteButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(pasteButton);

		undoButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(undoButton);

		redoButton.setPreferredSize(new java.awt.Dimension(20, 20));
		add(redoButton);
	}// </editor-fold>
	//GEN-END:initComponents

	private void cutButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton copyButton;
	private javax.swing.JButton cutButton;
	private javax.swing.JButton newWorkspaceButton;
	private javax.swing.JButton openFileButton;
	private javax.swing.JButton pasteButton;
	private javax.swing.JButton redoButton;
	private javax.swing.JButton saveAllButton;
	private javax.swing.JButton saveAsComponentButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JButton undoButton;
	// End of variables declaration//GEN-END:variables

}